### ISSUE TITLE
Cartel and Biker Rank based outfits

### ISSUE THREAD

**Issue by rdephillip** [rdephillip/CNX_FiveM_RP#22]
Cartel and Biker Rank based outfits

**Comment by lownignitus** [comment]
I actually have this partially worked on in my test server edit.

**Comment by rdephillip** [comment]
I have the code for it in place, I need bubba to help me pick the outfits for his bit... err uh... boys.

**Comment by lownignitus** [comment]
-.- I see... No respect...
